"use client";
import {useMemo,useState} from "react";
import {getCategory,services,type Lang,type Service} from "../data/evo";
import {demoAiGroups,demoAiScenarios,type DemoAiScenario} from "../data/demo-ai-scenarios";
import styles from "./demo-suite.module.css";

type Props={lang:Lang;onOpenService:(id:string)=>void;onBookService:(id:string)=>void};
const text={
ru:{title:"Умный консультант",lead:"Интерактивное демо будущего консультанта EVO на полном каталоге.",badge:"DEMO · БЕЗ РЕАЛЬНОГО ИИ",note:"Ответы и действия заранее запрограммированы. AI API не подключены.",hello:"Выберите готовый вопрос. Демо покажет подходящие услуги и передаст выбранную услугу в запись.",choose:"Выберите тему",rec:"Подходящие услуги EVO",details:"Подробнее",book:"Записаться",again:"Задать другой вопрос",follow:"Уточним запрос",who:"Вы",disclaimer:"Консультант помогает ориентироваться в услугах EVO и не заменяет консультацию специалиста. Окончательный выбор процедуры определяется после очной консультации."},
en:{title:"Smart consultant",lead:"Interactive demo of the future EVO consultant using the full catalog.",badge:"DEMO · NO REAL AI",note:"All answers and actions are pre-programmed. No AI API is connected.",hello:"Choose a ready-made question. The demo shows relevant services and passes a selected service into booking.",choose:"Choose a topic",rec:"Relevant EVO services",details:"Details",book:"Book",again:"Ask another question",follow:"Let’s narrow it down",who:"You",disclaimer:"The consultant helps you navigate EVO services and does not replace a specialist consultation. The final treatment choice is made after an in-person consultation."},
vi:{title:"Tư vấn thông minh",lead:"Bản demo tương tác của tư vấn viên EVO tương lai dựa trên danh mục đầy đủ.",badge:"DEMO · KHÔNG CÓ AI THẬT",note:"Tất cả câu trả lời và thao tác đã được lập trình sẵn. Không kết nối API AI.",hello:"Chọn câu hỏi có sẵn. Demo hiển thị dịch vụ phù hợp và chuyển dịch vụ đã chọn sang đặt lịch.",choose:"Chọn chủ đề",rec:"Dịch vụ EVO phù hợp",details:"Chi tiết",book:"Đặt lịch",again:"Hỏi câu khác",follow:"Hãy làm rõ nhu cầu",who:"Bạn",disclaimer:"Tư vấn viên giúp định hướng dịch vụ EVO và không thay thế tư vấn chuyên gia. Lựa chọn cuối cùng được quyết định sau tư vấn trực tiếp."}
} as const;
const norm=(s:string)=>s.toLocaleLowerCase().replace(/ё/g,"е");
function score(service:Service,keywords:string[],groupId:string){const c=getCategory(service.categoryId);if(c?.groupId!==groupId)return 0;const hay=norm(Object.values(service.name).join(" "));return keywords.reduce((n,k)=>n+(hay.includes(norm(k))?1:0),0)}
function picks(s:DemoAiScenario,keywords:string[]){const found=services.map(service=>({service,n:score(service,keywords,s.groupId)})).filter(x=>x.n).sort((a,b)=>b.n-a.n).map(x=>x.service);for(const service of services){if(found.length>=4)break;const c=getCategory(service.categoryId);if(c?.groupId===s.groupId&&!found.some(x=>x.id===service.id))found.push(service)}return found.slice(0,4)}
export default function DemoAiConsultant({lang,onOpenService,onBookService}:Props){const x=text[lang];const [scenarioId,setScenarioId]=useState("");const [followId,setFollowId]=useState("");const scenario=demoAiScenarios.find(s=>s.id===scenarioId);const follow=scenario?.followup?.options.find(o=>o.id===followId);const rec=useMemo(()=>scenario?picks(scenario,follow?.keywords||scenario.keywords):[],[scenario,follow]);const reset=()=>{setScenarioId("");setFollowId("")};return <section className="page" data-testid="demo-ai"><div className="pageHead"><small>EVO AI CONSULTANT · DEMO</small><h1>{x.title}</h1><p>{x.lead}</p></div><div className={styles.demoBanner}><b>{x.badge}</b><span>{x.note}</span></div><div className={styles.aiShell}><div className={styles.aiIntro}><span>✦</span><p>{x.hello}</p></div>{!scenario?<><div className={styles.sectionLabel}>{x.choose}</div><div className={styles.aiTopics}>{demoAiGroups.map(g=><section key={g.id} className={styles.aiTopic}><h2>{g.title[lang]}</h2><div className={styles.questionGrid}>{demoAiScenarios.filter(s=>s.groupId===g.id).map(s=><button data-testid={`ai-question-${s.id}`} key={s.id} onClick={()=>setScenarioId(s.id)}>{s.question[lang]}<span>→</span></button>)}</div></section>)}</div></>:<div className={styles.aiConversation}><div className={`${styles.aiMessage} ${styles.userMessage}`}><small>{x.who}</small><p>{scenario.question[lang]}</p></div><div className={`${styles.aiMessage} ${styles.consultantMessage}`}><small>EVO · DEMO</small><p>{scenario.answer[lang]}</p></div>{scenario.followup&&!follow&&<div className={styles.followupBox} data-testid="ai-followup"><small>{x.follow}</small><h3>{scenario.followup.prompt[lang]}</h3><div>{scenario.followup.options.map(o=><button key={o.id} onClick={()=>setFollowId(o.id)}>{o.label[lang]}</button>)}</div></div>}{follow&&<div className={`${styles.aiMessage} ${styles.consultantMessage}`}><small>EVO · DEMO</small><p>{follow.answer[lang]}</p></div>}{(!scenario.followup||follow)&&<section className={styles.recommendations} data-testid="ai-recommendations"><div className={styles.sectionLabel}>{x.rec}</div><div className={styles.recommendationGrid}>{rec.map(service=>{const c=getCategory(service.categoryId);return <article key={service.id} className={styles.recommendationCard}><img src={service.image} alt=""/><div><small>{c?.name[lang]}</small><h3>{service.name[lang]}</h3><p>{service.price[lang]}{service.duration?` · ${service.duration} min`:""}</p></div><div className={styles.cardActions}><button className={styles.secondaryButton} onClick={()=>onOpenService(service.id)}>{x.details}</button><button data-testid={`ai-book-${service.id}`} className={styles.primaryButton} onClick={()=>onBookService(service.id)}>{x.book}</button></div></article>})}</div></section>}<button className={styles.restartButton} onClick={reset}>↺ {x.again}</button></div>}</div><div className={styles.disclaimer}><b>DEMO</b><p>{x.disclaimer}</p></div></section>}
