"use client";
import {useMemo,useState} from "react";
import {getCategory,getGroup,getService,getSpecialist,groups,services,specialists,type Lang} from "../data/evo";
import type {DemoAppointment} from "../lib/storage";
import styles from "./demo-suite.module.css";

type Props={lang:Lang;appointments:DemoAppointment[];onBack:()=>void};
type Tab="overview"|"appointments"|"clients"|"catalog"|"specialists"|"broadcasts"|"automation"|"analytics";
type Status="new"|"confirmed"|"arrived"|"completed"|"cancelled";
type DemoRow={id:string;name:string;phone:string;lang:string;serviceId:string;specialistId:string;time:string;status:Status;source:string};
type Client={id:string;name:string;phone:string;telegram:string;language:string;visits:number;spend:string;interests:string[];last:string;tag:string;note:string;source:string};
const pick=(needle:string)=>services.find(s=>Object.values(s.name).some(v=>v.toLowerCase().includes(needle.toLowerCase())))||services[0];
const serviceRows=()=>[
  ["a1","Анна Петрова","+84 90 111 22 33","RU",pick("AirTouch"),"10:00","new","Telegram"],
  ["a2","Nguyễn Thu Hà","+84 93 222 44 55","VI",pick("Маникюр"),"10:30","confirmed","Instagram"],
  ["a3","Michael Reed","+84 96 333 55 66","EN",pick("laser"),"11:30","confirmed","Google Maps"],
  ["a4","Елена Соколова","+84 90 444 66 77","RU",pick("Ботокс Full Face"),"13:00","arrived","Telegram"],
  ["a5","Trần Mai","+84 91 555 77 88","VI",pick("Педикюр"),"14:30","completed","Referral"],
  ["a6","Sophie Martin","+84 92 666 88 99","EN",pick("tattoo"),"16:00","new","Instagram"]
].map(([id,name,phone,lang,service,time,status,source])=>{const s=service as ReturnType<typeof pick>;return {id,name,phone,lang,serviceId:s.id,specialistId:s.specialistIds[0]||specialists[0]?.id||"",time,status,source} as DemoRow});
const clients:Client[]=[
{id:"c1",name:"Анна Петрова",phone:"+84 90 111 22 33",telegram:"@anna_ntr",language:"RU",visits:8,spend:"13 400 000 ₫",interests:["hair","cosmetology"],last:"18.08",tag:"VIP",note:"Окрашивание каждые 5–6 недель. Интересуется восстановлением волос.",source:"Telegram"},
{id:"c2",name:"Nguyễn Thu Hà",phone:"+84 93 222 44 55",telegram:"@thuha",language:"VI",visits:5,spend:"6 800 000 ₫",interests:["nails","brows-pmu"],last:"21.08",tag:"Regular",note:"Manicure + brow services. Prefers afternoon appointments.",source:"Instagram"},
{id:"c3",name:"Michael Reed",phone:"+84 96 333 55 66",telegram:"@mreed",language:"EN",visits:3,spend:"8 900 000 ₫",interests:["laser"],last:"12.08",tag:"Regular",note:"Laser course. Next visit usually after 4–5 weeks.",source:"Google Maps"},
{id:"c4",name:"Елена Соколова",phone:"+84 90 444 66 77",telegram:"@elena_s",language:"RU",visits:6,spend:"17 200 000 ₫",interests:["cosmetology"],last:"24.08",tag:"VIP",note:"Интерес к качеству кожи и аппаратным процедурам.",source:"Telegram"},
{id:"c5",name:"Trần Mai",phone:"+84 91 555 77 88",telegram:"@tranmai",language:"VI",visits:2,spend:"2 100 000 ₫",interests:["nails"],last:"25.08",tag:"New",note:"New client. Pedicure and podology interest.",source:"Referral"},
{id:"c6",name:"Sophie Martin",phone:"+84 92 666 88 99",telegram:"@sophie_m",language:"EN",visits:1,spend:"1 500 000 ₫",interests:["tattoo-body"],last:"20.08",tag:"New",note:"Asked about a small art tattoo and laser removal.",source:"Instagram"}
];
const statusLabels={ru:{new:"Новая",confirmed:"Подтверждена",arrived:"Клиент пришёл",completed:"Завершена",cancelled:"Отменена"},en:{new:"New",confirmed:"Confirmed",arrived:"Arrived",completed:"Completed",cancelled:"Cancelled"},vi:{new:"Mới",confirmed:"Đã xác nhận",arrived:"Đã đến",completed:"Hoàn tất",cancelled:"Đã hủy"}} as const;
const T=(lang:Lang,ru:string,en:string,vi:string)=>lang==="ru"?ru:lang==="vi"?vi:en;
export default function DemoAdmin({lang,appointments,onBack}:Props){
 const [tab,setTab]=useState<Tab>("overview"),[rows,setRows]=useState<DemoRow[]>(serviceRows),[statusFilter,setStatusFilter]=useState<Status|"all">("all"),[groupFilter,setGroupFilter]=useState("all"),[clientSearch,setClientSearch]=useState(""),[selectedClient,setSelectedClient]=useState<Client|null>(null),[catalogSearch,setCatalogSearch]=useState(""),[catalogGroup,setCatalogGroup]=useState("all"),[flags,setFlags]=useState<Record<string,{hidden?:boolean;popular?:boolean;promo?:boolean}>>({}),[audience,setAudience]=useState("all"),[channel,setChannel]=useState("Telegram"),[message,setMessage]=useState(""),[broadcastResult,setBroadcastResult]=useState(""),[toast,setToast]=useState(""),[automation,setAutomation]=useState<Record<string,boolean>>({r24:true,r2:true,review:true,repeat30:false,return60:true,birthday:false});
 const status=statusLabels[lang];
 const tabs:Array<[Tab,string]>= [["overview",T(lang,"Обзор","Overview","Tổng quan")],["appointments",T(lang,"Записи","Appointments","Lịch hẹn")],["clients",T(lang,"Клиенты","Clients","Khách hàng")],["catalog",T(lang,"Каталог","Catalog","Danh mục")],["specialists",T(lang,"Специалисты","Specialists","Chuyên gia")],["broadcasts",T(lang,"Рассылки","Broadcasts","Chiến dịch")],["automation",T(lang,"Автоматизация","Automation","Tự động hóa")],["analytics",T(lang,"Аналитика","Analytics","Phân tích")]];
 const allRows=useMemo(()=>[...appointments.map((a,i)=>({id:`local-${a.id}`,name:a.name,phone:a.phone,lang:lang.toUpperCase(),serviceId:a.serviceId,specialistId:a.specialistId,time:a.time,status:"new" as Status,source:"MiniApp DEMO"})),...rows],[appointments,rows,lang]);
 const visibleRows=useMemo(()=>allRows.filter(r=>{const c=getCategory(getService(r.serviceId)?.categoryId||"");return (statusFilter==="all"||r.status===statusFilter)&&(groupFilter==="all"||c?.groupId===groupFilter)}),[allRows,statusFilter,groupFilter]);
 const visibleClients=clients.filter(c=>`${c.name} ${c.phone} ${c.telegram}`.toLowerCase().includes(clientSearch.toLowerCase()));
 const visibleCatalog=services.filter(s=>{const c=getCategory(s.categoryId);const q=catalogSearch.toLowerCase();return (catalogGroup==="all"||c?.groupId===catalogGroup)&&(!q||Object.values(s.name).join(" ").toLowerCase().includes(q))}).slice(0,24);
 const setRowStatus=(id:string,next:Status)=>{setRows(v=>v.map(r=>r.id===id?{...r,status:next}:r));setToast(T(lang,"Демо-статус обновлён","Demo status updated","Đã cập nhật trạng thái demo"))};
 const demoMessage=(name:string)=>setToast(T(lang,`DEMO: сообщение для ${name} подготовлено`,`DEMO: message for ${name} prepared`,`DEMO: đã chuẩn bị tin nhắn cho ${name}`));
 const openClient=(name:string)=>setSelectedClient(clients.find(c=>c.name===name)||clients[0]);
 const audienceCount=audience==="all"?126:audience==="inactive"?37:audience==="vip"?18:42;
 return <section className="page" data-testid="demo-admin">
  <button className="back" onClick={onBack}>← {T(lang,"Назад","Back","Quay lại")}</button>
  <div className="pageHead"><small>EVO CONTROL · DEMO ADMIN</small><h1>{T(lang,"Управление EVO","EVO control","Quản lý EVO")}</h1><p>{T(lang,"Демонстрация будущей бизнес-части: записи, клиенты, каталог, рассылки, автоматизация и аналитика.","Preview of the future business workspace: appointments, clients, catalog, campaigns, automation and analytics.","Bản demo khu vực quản trị tương lai: lịch hẹn, khách hàng, danh mục, chiến dịch, tự động hóa và phân tích.")}</p></div>
  <div className={styles.demoBanner}><b>DEMO ADMIN</b><span>{T(lang,"Все данные и действия локальные. Ничего не отправляется в Altegio, Telegram, SMS или Email.","All data and actions are local. Nothing is sent to Altegio, Telegram, SMS or Email.","Tất cả dữ liệu và thao tác đều cục bộ. Không gửi gì tới Altegio, Telegram, SMS hay Email.")}</span></div>
  <div className={styles.adminTabs} role="tablist">{tabs.map(([id,label])=><button data-testid={`admin-tab-${id}`} className={tab===id?styles.activeTab:""} key={id} onClick={()=>setTab(id)}>{label}</button>)}</div>
  {toast&&<button className={styles.toast} onClick={()=>setToast("")}>{toast}<span>×</span></button>}

  {tab==="overview"&&<div data-testid="admin-overview"><div className={styles.metricGrid}>{[["18",T(lang,"Записей сегодня","Appointments today","Lịch hôm nay")],["126",T(lang,"За неделю","This week","Tuần này")],["42",T(lang,"Новых клиентов","New clients","Khách mới")],["68%",T(lang,"Повторные","Returning","Quay lại")],["3",T(lang,"Отмены","Cancellations","Hủy")],["156,8 млн ₫",T(lang,"Выручка · demo","Revenue · demo","Doanh thu · demo")]].map(([v,l])=><article key={l}><b>{v}</b><small>{l}</small></article>)}</div><div className={styles.adminCard}><div className={styles.cardHead}><div><small>{T(lang,"СЕГОДНЯ","TODAY","HÔM NAY")}</small><h2>{T(lang,"Загрузка и приоритеты","Load & priorities","Công suất & ưu tiên")}</h2></div><b>82%</b></div><div className={styles.progress}><i style={{width:"82%"}}/></div><div className={styles.insightList}><p><b>10:00–13:00</b><span>{T(lang,"Высокая загрузка Hair + Nails","High load: Hair + Nails","Công suất cao: Hair + Nails")}</span></p><p><b>15:00–17:00</b><span>{T(lang,"Есть окна в косметологии","Open capacity in cosmetology","Còn chỗ ở thẩm mỹ da")}</span></p><p><b>37</b><span>{T(lang,"Клиентов для реактивации · demo","Clients to reactivate · demo","Khách cần kích hoạt lại · demo")}</span></p></div></div><div className={styles.adminCard}><div className={styles.cardHead}><div><small>DEMO AI INSIGHTS</small><h2>{T(lang,"Подсказки владельцу","Owner insights","Gợi ý cho chủ doanh nghiệp")}</h2></div></div><div className={styles.insightList}><p><b>Hair</b><span>{T(lang,"Повторные окрашивания формируют стабильный цикл 5–6 недель.","Repeat coloring creates a stable 5–6 week cycle.","Nhuộm lặp lại tạo chu kỳ ổn định 5–6 tuần.")}</span></p><p><b>Laser</b><span>{T(lang,"12 клиентов подходят для следующего визита по курсу.","12 clients are due for the next course visit.","12 khách đến kỳ cho buổi tiếp theo trong liệu trình.")}</span></p><p><b>Nails</b><span>{T(lang,"Комбо маникюр + педикюр показывает высокий потенциал допродажи.","Manicure + pedicure combo shows strong upsell potential.","Combo manicure + pedicure có tiềm năng bán thêm cao.")}</span></p></div></div></div>}

  {tab==="appointments"&&<div data-testid="admin-appointments"><div className={styles.filterRow}><select value={statusFilter} onChange={e=>setStatusFilter(e.target.value as Status|"all")}><option value="all">{T(lang,"Все статусы","All statuses","Tất cả trạng thái")}</option>{(Object.keys(status) as Status[]).map(s=><option key={s} value={s}>{status[s]}</option>)}</select><select value={groupFilter} onChange={e=>setGroupFilter(e.target.value)}><option value="all">{T(lang,"Все направления","All directions","Tất cả nhóm")}</option>{groups.map(g=><option key={g.id} value={g.id}>{g.name[lang]}</option>)}</select></div><div className={styles.adminList}>{visibleRows.map(r=>{const s=getService(r.serviceId),sp=getSpecialist(r.specialistId);return <article className={styles.appointmentCard} key={r.id}><div className={styles.cardHead}><div><small>{r.time} · {r.source}</small><h3>{r.name}</h3></div><span className={`${styles.statusBadge} ${styles[r.status]}`}>{status[r.status]}</span></div><p><b>{s?.name[lang]}</b><small>{sp?.name[lang]||T(lang,"Специалист EVO","EVO specialist","Chuyên gia EVO")} · {s?.price[lang]}</small></p><div className={styles.cardActions}><button onClick={()=>setRowStatus(r.id,"confirmed")}>{T(lang,"Подтвердить","Confirm","Xác nhận")}</button><button onClick={()=>setRowStatus(r.id,"cancelled")}>{T(lang,"Отменить","Cancel","Hủy")}</button><button onClick={()=>setToast(T(lang,"DEMO: время перенесено на следующий свободный слот","DEMO: moved to the next available slot","DEMO: đã chuyển sang khung giờ trống tiếp theo"))}>{T(lang,"Перенести","Reschedule","Đổi lịch")}</button><button onClick={()=>openClient(r.name)}>{T(lang,"Клиент","Client","Khách")}</button><button onClick={()=>demoMessage(r.name)}>{T(lang,"Написать","Message","Nhắn tin")}</button></div></article>})}</div></div>}

  {tab==="clients"&&<div data-testid="admin-clients"><label className={styles.searchBox}><span>⌕</span><input value={clientSearch} onChange={e=>setClientSearch(e.target.value)} placeholder={T(lang,"Поиск клиента","Search clients","Tìm khách hàng")}/></label><div className={styles.clientSummary}><span><b>1 248</b><small>{T(lang,"Всего · demo","Total · demo","Tổng · demo")}</small></span><span><b>84</b><small>{T(lang,"VIP","VIP","VIP")}</small></span><span><b>37</b><small>{T(lang,"Давно не были","Inactive","Lâu chưa quay lại")}</small></span></div><div className={styles.adminList}>{visibleClients.map(c=><button className={styles.clientRow} key={c.id} onClick={()=>setSelectedClient(c)}><span className={styles.avatar}>{c.name[0]}</span><span><b>{c.name}</b><small>{c.tag} · {c.visits} {T(lang,"визитов","visits","lần")}</small><em>{c.interests.map(id=>getGroup(id)?.name[lang]||id).join(" · ")}</em></span><strong>→</strong></button>)}</div></div>}

  {tab==="catalog"&&<div data-testid="admin-catalog"><div className={styles.filterRow}><input value={catalogSearch} onChange={e=>setCatalogSearch(e.target.value)} placeholder={T(lang,"Поиск по 257 услугам","Search 257 services","Tìm trong 257 dịch vụ")}/><select value={catalogGroup} onChange={e=>setCatalogGroup(e.target.value)}><option value="all">{T(lang,"Все направления","All directions","Tất cả nhóm")}</option>{groups.map(g=><option key={g.id} value={g.id}>{g.name[lang]}</option>)}</select></div><p className={styles.microcopy}>{T(lang,"DEMO: изменения каталога не отправляются в Altegio.","DEMO: catalog changes are not sent to Altegio.","DEMO: thay đổi danh mục không được gửi tới Altegio.")}</p><div className={styles.adminList}>{visibleCatalog.map(s=>{const f=flags[s.id]||{};return <article className={styles.catalogAdminRow} key={s.id}><img src={s.image} alt=""/><div><small>{getCategory(s.categoryId)?.name[lang]}</small><b>{s.name[lang]}</b><em>{s.price[lang]}</em></div><div className={styles.flagButtons}><button className={f.hidden?styles.flagOn:""} onClick={()=>setFlags(v=>({...v,[s.id]:{...v[s.id],hidden:!v[s.id]?.hidden}}))}>{T(lang,"Скрыть","Hide","Ẩn")}</button><button className={f.popular?styles.flagOn:""} onClick={()=>setFlags(v=>({...v,[s.id]:{...v[s.id],popular:!v[s.id]?.popular}}))}>★</button><button className={f.promo?styles.flagOn:""} onClick={()=>setFlags(v=>({...v,[s.id]:{...v[s.id],promo:!v[s.id]?.promo}}))}>%</button></div></article>})}</div></div>}

  {tab==="specialists"&&<div data-testid="admin-specialists"><div className={styles.specialistAdminGrid}>{specialists.filter(s=>!s.demo).map((sp,i)=><article key={sp.id}><img src={sp.image} alt=""/><div><h3>{sp.name[lang]}</h3><p>{sp.role[lang]}</p><div className={styles.specialistMetrics}><span><b>{4+(i%6)}</b><small>{T(lang,"сегодня","today","hôm nay")}</small></span><span><b>{62+(i*3)%35}%</b><small>{T(lang,"загрузка","load","công suất")}</small></span><span><b>{(4.7+(i%3)*.1).toFixed(1)}</b><small>{T(lang,"рейтинг · demo","rating · demo","đánh giá · demo")}</small></span></div></div></article>)}</div></div>}

  {tab==="broadcasts"&&<div data-testid="admin-broadcast"><div className={styles.adminCard}><div className={styles.cardHead}><div><small>CAMPAIGN BUILDER · DEMO</small><h2>{T(lang,"Новая рассылка","New campaign","Chiến dịch mới")}</h2></div></div><div className={styles.formGrid}><label>{T(lang,"Аудитория","Audience","Đối tượng")}<select value={audience} onChange={e=>setAudience(e.target.value)}><option value="all">{T(lang,"Все клиенты","All clients","Tất cả khách")}</option><option value="direction">{T(lang,"По направлению","By direction","Theo nhóm dịch vụ")}</option><option value="inactive">{T(lang,"Давно не посещали","Inactive clients","Khách lâu chưa quay lại")}</option><option value="vip">VIP</option></select></label><label>{T(lang,"Канал","Channel","Kênh")}<select value={channel} onChange={e=>setChannel(e.target.value)}><option>Telegram</option><option>SMS</option><option>Email</option></select></label><label className={styles.fullField}>{T(lang,"Текст","Message","Nội dung")}<textarea value={message} onChange={e=>setMessage(e.target.value)} placeholder={T(lang,"Например: у EVO появились свободные окна…","For example: EVO has open appointment slots…","Ví dụ: EVO đang có khung giờ trống…")}/></label></div><div className={styles.previewBox}><small>{T(lang,"ПРЕДПРОСМОТР","PREVIEW","XEM TRƯỚC")} · {channel}</small><p>{message||T(lang,"Текст рассылки появится здесь.","Campaign message will appear here.","Nội dung chiến dịch sẽ xuất hiện ở đây.")}</p></div><button className={styles.primaryButton} disabled={!message.trim()} onClick={()=>setBroadcastResult(T(lang,`Demo: рассылка подготовлена для ${audienceCount} клиентов.`,`Demo: campaign prepared for ${audienceCount} clients.`,`Demo: chiến dịch đã chuẩn bị cho ${audienceCount} khách.`))}>{T(lang,"Отправить DEMO","Send DEMO","Gửi DEMO")}</button>{broadcastResult&&<div className={styles.successDemo}>✓ {broadcastResult}</div>}</div></div>}

  {tab==="automation"&&<div data-testid="admin-automation"><p className={styles.microcopy}>{T(lang,"Настройки демонстрационные. После подключения каналов эти правила смогут работать автоматически.","These settings are demonstrational. After channel integration, the rules can run automatically.","Các cài đặt này là demo. Sau khi kết nối kênh, các quy tắc có thể chạy tự động.")}</p><div className={styles.automationList}>{[["r24",T(lang,"Напомнить о записи за 24 часа","Appointment reminder 24h before","Nhắc lịch trước 24 giờ")],["r2",T(lang,"Напомнить за 2 часа","Reminder 2h before","Nhắc trước 2 giờ")],["review",T(lang,"Запросить отзыв после визита","Request a review after visit","Yêu cầu đánh giá sau buổi hẹn")],["repeat30",T(lang,"Предложить повторный визит через 30 дней","Suggest repeat visit after 30 days","Gợi ý quay lại sau 30 ngày")],["return60",T(lang,"Вернуть клиента через 60 дней","Reactivate client after 60 days","Kích hoạt lại sau 60 ngày")],["birthday",T(lang,"Поздравить с днём рождения","Birthday message","Tin nhắn sinh nhật")]].map(([id,label])=><button key={id} onClick={()=>setAutomation(v=>({...v,[id]:!v[id]}))}><span><b>{label}</b><small>DEMO RULE</small></span><i className={automation[id]?styles.toggleOn:""}><u/></i></button>)}</div></div>}

  {tab==="analytics"&&<div data-testid="admin-analytics"><div className={styles.metricGrid}>{[["2,75 млн ₫",T(lang,"Средний чек","Average ticket","Giá trị TB")],["68%",T(lang,"Повторные","Returning","Quay lại")],["82%",T(lang,"Загрузка","Utilization","Công suất")],["4,9",T(lang,"Рейтинг · demo","Rating · demo","Đánh giá · demo")]].map(([v,l])=><article key={l}><b>{v}</b><small>{l}</small></article>)}</div><div className={styles.adminCard}><h2>{T(lang,"Популярные направления","Top directions","Nhóm phổ biến")}</h2>{[["Hair",86],["Cosmetology",74],["Nails",68],["Laser",51],["Brows / PMU",43]].map(([label,value])=><div className={styles.barRow} key={label}><span>{label}</span><i><u style={{width:`${value}%`}}/></i><b>{value}</b></div>)}</div><div className={styles.adminCard}><h2>{T(lang,"Источники клиентов","Client sources","Nguồn khách")}</h2>{[["Instagram","34%"],["Telegram","29%"],["Google Maps","21%"],[T(lang,"Рекомендации","Referrals","Giới thiệu"),"16%"]].map(([a,b])=><div className={styles.sourceLine} key={a}><span>{a}</span><b>{b}</b></div>)}</div></div>}

  {selectedClient&&<div className={styles.modalOverlay} onClick={()=>setSelectedClient(null)}><article className={styles.clientModal} role="dialog" aria-modal="true" onClick={e=>e.stopPropagation()} data-testid="admin-client-card"><div className={styles.cardHead}><div><small>{T(lang,"КАРТОЧКА КЛИЕНТА","CLIENT PROFILE","HỒ SƠ KHÁCH")}</small><h2>{selectedClient.name}</h2></div><button onClick={()=>setSelectedClient(null)}>×</button></div><div className={styles.profileFacts}><span><small>{T(lang,"Телефон","Phone","Điện thoại")}</small><b>{selectedClient.phone}</b></span><span><small>Telegram</small><b>{selectedClient.telegram}</b></span><span><small>{T(lang,"Язык","Language","Ngôn ngữ")}</small><b>{selectedClient.language}</b></span><span><small>{T(lang,"Визиты","Visits","Lần đến")}</small><b>{selectedClient.visits}</b></span><span><small>{T(lang,"Сумма · demo","Spend · demo","Chi tiêu · demo")}</small><b>{selectedClient.spend}</b></span><span><small>{T(lang,"Последний визит","Last visit","Lần gần nhất")}</small><b>{selectedClient.last}</b></span></div><div className={styles.adminCard}><small>{T(lang,"ИНТЕРЕСЫ","INTERESTS","SỞ THÍCH")}</small><p>{selectedClient.interests.map(id=>getGroup(id)?.name[lang]||id).join(" · ")}</p></div><div className={styles.adminCard}><small>{T(lang,"ЗАМЕТКА АДМИНИСТРАТОРА","ADMIN NOTE","GHI CHÚ QUẢN TRỊ")}</small><p>{selectedClient.note}</p></div><div className={styles.adminCard}><small>DEMO AI INSIGHTS</small><div className={styles.insightList}><p><b>↗</b><span>{T(lang,"Поведенческая подсказка строится по истории визитов и интересам клиента.","Behavior insight is based on visit history and client interests.","Gợi ý hành vi dựa trên lịch sử ghé thăm và sở thích khách hàng.")}</span></p><p><b>○</b><span>{T(lang,"Можно подготовить персональное предложение или напоминание. Действие сейчас только демо.","A personalized offer or reminder can be prepared. This action is demo-only now.","Có thể chuẩn bị ưu đãi hoặc lời nhắc cá nhân. Hiện chỉ là demo.")}</span></p></div></div><button className={styles.primaryButton} onClick={()=>demoMessage(selectedClient.name)}>{T(lang,"Подготовить сообщение DEMO","Prepare DEMO message","Chuẩn bị tin nhắn DEMO")}</button></article></div>}
 </section>
}
