"use client";
import {useEffect,useState} from "react";
type Lang="ru"|"en"|"vi"; type Screen="home"|"services"|"booking"|"ai"|"profile";
const BOOK="https://n1324284.alteg.io/company/1258225/personal/menu?o=";
const MEDIA="https://274418.selcdn.ru/cv08300-33250f0d-0664-43fc-9dbf-9d89738d114e/uploads/111003/";
const services=[
 {ru:"Уход и обновление кожи",en:"Skin care & renewal",vi:"Chăm sóc & tái tạo da",noteRu:"Чистка лица и пилинг",noteEn:"Facial cleansing and peeling",noteVi:"Làm sạch da mặt và peel da",img:MEDIA+"d0719a5c-c5bf-40b4-a29d-47fd959e0bcd.png"},
 {ru:"Аппаратная косметология",en:"Device cosmetology",vi:"Thẩm mỹ công nghệ cao",noteRu:"SMAS-лифтинг",noteEn:"SMAS lifting",noteVi:"Nâng cơ SMAS",img:MEDIA+"5550bb7b-ccf0-4686-8eb3-ee9ef80db99b.jpg"},
 {ru:"Инъекционная косметология",en:"Injectable cosmetology",vi:"Thẩm mỹ tiêm",noteRu:"Биоревитализация · мезотерапия · ботулинотерапия",noteEn:"Biorevitalization · mesotherapy · botulinum",noteVi:"Biorevitalization · mesotherapy · botulinum",img:MEDIA+"6d50a4c0-43fa-4bd8-9d52-af2e539e81f6.webp"},
 {ru:"Контуры и качество кожи",en:"Contours & skin quality",vi:"Đường nét & chất lượng da",noteRu:"Контурная пластика и коллаген",noteEn:"Contour correction & collagen",noteVi:"Tạo đường nét & collagen",img:MEDIA+"b6040595-5b9a-4de2-8676-b835b5fbf79c.jpg"},
 {ru:"Нитевой лифтинг",en:"Thread lifting",vi:"Căng chỉ",noteRu:"Каркас и стимуляция коллагена",noteEn:"Support & collagen stimulation",noteVi:"Nâng đỡ & kích thích collagen",img:MEDIA+"4349a451-6388-4f69-8e82-83b1e70c1f9b.png"},
 {ru:"Восстановительные программы",en:"Restorative programs",vi:"Chương trình phục hồi",noteRu:"Плацентарная и инфузионная терапия",noteEn:"Placental & infusion therapy",noteVi:"Liệu pháp nhau thai & truyền dịch",img:MEDIA+"93f4a6b9-eaa3-4854-b4fb-05f4ce8d3f54.png"}
];
const tr={
 ru:{hero:"Косметология EVO в Нячанге",lead:"Процедуры, специалисты и запись — в одном мобильном интерфейсе.",services:"Услуги",book:"Записаться",specialists:"Специалисты",popular:"Популярные направления",all:"Смотреть все",open:"Онлайн-запись открыта",consult:"Консультация косметолога",ask:"Спросить ИИ",aiLead:"Помогу сориентироваться по направлениям EVO. Медицинские решения — после консультации специалиста.",ph:"Что выбрать для качества кожи?",send:"Спросить",profile:"Профиль",booking:"Запись",bookingLead:"Выберите услугу и время в официальной системе EVO.",external:"Открыть запись EVO",price:"Актуальную стоимость уточняйте при записи.",home:"Главная"},
 en:{hero:"EVO cosmetology in Nha Trang",lead:"Treatments, specialists and booking in one mobile interface.",services:"Services",book:"Book",specialists:"Specialists",popular:"Popular directions",all:"View all",open:"Online booking available",consult:"Cosmetology consultation",ask:"Ask AI",aiLead:"I can help you navigate EVO services. Medical decisions require a specialist consultation.",ph:"What may help skin quality?",send:"Ask",profile:"Profile",booking:"Booking",bookingLead:"Choose a service and time in EVO's official booking system.",external:"Open EVO booking",price:"Confirm the current price when booking.",home:"Home"},
 vi:{hero:"Thẩm mỹ EVO tại Nha Trang",lead:"Dịch vụ, chuyên gia và đặt lịch trong một giao diện di động.",services:"Dịch vụ",book:"Đặt lịch",specialists:"Chuyên gia",popular:"Dịch vụ nổi bật",all:"Xem tất cả",open:"Đặt lịch trực tuyến",consult:"Tư vấn thẩm mỹ",ask:"Hỏi AI",aiLead:"Tôi có thể giúp bạn tìm hiểu dịch vụ EVO. Quyết định y khoa cần tư vấn chuyên gia.",ph:"Dịch vụ nào cho chất lượng da?",send:"Hỏi",profile:"Hồ sơ",booking:"Đặt lịch",bookingLead:"Chọn dịch vụ và thời gian trong hệ thống chính thức của EVO.",external:"Mở đặt lịch EVO",price:"Xác nhận giá hiện tại khi đặt lịch.",home:"Trang chủ"}
};
function browserLang():Lang{if(typeof navigator==="undefined")return"ru";const x=navigator.language.toLowerCase();return x.startsWith("vi")?"vi":x.startsWith("en")?"en":"ru"}
export default function App(){const[lang,setLang]=useState<Lang>("ru");const[screen,setScreen]=useState<Screen>("home");const[q,setQ]=useState("");const[a,setA]=useState("");useEffect(()=>{const s=localStorage.getItem("evo-lang") as Lang|null;setLang(s&&["ru","en","vi"].includes(s)?s:browserLang())},[]);const t=tr[lang];const name=(s:any)=>s[lang];const note=(s:any)=>lang==="ru"?s.noteRu:lang==="en"?s.noteEn:s.noteVi;const change=(l:Lang)=>{setLang(l);localStorage.setItem("evo-lang",l);document.documentElement.lang=l};const ask=()=>{if(!q.trim())return;setA(lang==="ru"?"Для качества кожи в EVO есть уходовые, аппаратные, инъекционные и коллагеностимулирующие направления. Точный вариант подбирает косметолог после оценки кожи и противопоказаний.":lang==="en"?"EVO offers skin care, device, injectable and collagen-stimulating options. A cosmetologist should choose the exact approach after assessing your skin and contraindications.":"EVO có chăm sóc da, công nghệ cao, thẩm mỹ tiêm và kích thích collagen. Chuyên gia sẽ chọn phương án phù hợp sau khi đánh giá da và chống chỉ định.")};return <main className="shell">
<header><button className="brand" onClick={()=>setScreen("home")}><span>E</span><b>EVO<small>BEAUTY SPACE · NHA TRANG</small></b></button><div className="langs">{(["ru","en","vi"] as Lang[]).map(l=><button key={l} onClick={()=>change(l)} className={lang===l?"on":""}>{l.toUpperCase()}</button>)}</div></header>
<section className="content">
{screen==="home"&&<><div className="hero"><div className="heroText"><small>EVO BEAUTY SPACE</small><h1>{t.hero}</h1><p>{t.lead}</p><div><button onClick={()=>setScreen("booking")}>{t.book}</button><button className="ghost" onClick={()=>setScreen("services")}>{t.services}</button></div></div></div><button className="status" onClick={()=>setScreen("booking")}><i/><span><b>{t.open}</b><small>{t.consult}</small></span><em>→</em></button><div className="title"><h2>{t.popular}</h2><button onClick={()=>setScreen("services")}>{t.all}</button></div><div className="grid">{services.slice(0,4).map((s,i)=><button className="card" key={i} onClick={()=>setScreen("booking")}><img src={s.img} alt=""/><span><b>{name(s)}</b><small>{note(s)}</small></span></button>)}</div><div className="title"><h2>{t.specialists}</h2></div><div className="experts">{["Cosmetology & skin care","Device & aesthetic procedures","Thread lifting"].map((x,i)=><div key={x}><span>0{i+1}</span><b>{x}</b></div>)}</div></>}
{screen==="services"&&<div className="page"><small>EVO CARE</small><h1>{t.services}</h1><p>{t.price}</p><div className="list">{services.map((s,i)=><button key={i} onClick={()=>setScreen("booking")}><img src={s.img} alt=""/><span><b>{name(s)}</b><small>{note(s)}</small></span><em>→</em></button>)}</div></div>}
{screen==="booking"&&<div className="page"><small>EVO · ALTEGIO</small><h1>{t.booking}</h1><p>{t.bookingLead}</p><div className="booking"><div className="photo"/><div><b>{t.consult}</b><p>{t.price}</p><a href={BOOK} target="_blank" rel="noreferrer">{t.external}</a></div></div><div className="contact"><b>EVO Beauty Space</b><p>40 Đ. Bắc Sơn, Vĩnh Hải, Nha Trang</p><a href="tel:+84905080200">+84 905 080 200</a><br/><a href="mailto:evo.beauty.space@gmail.com">evo.beauty.space@gmail.com</a></div></div>}
{screen==="ai"&&<div className="page"><small>EVO AI · DEMO</small><h1>{t.ask}</h1><p>{t.aiLead}</p><div className="chat"><div>{t.aiLead}</div>{a&&<div className="answer">{a}</div>}<section><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&ask()} placeholder={t.ph}/><button onClick={ask}>{t.send}</button></section></div></div>}
{screen==="profile"&&<div className="page"><small>EVO CLIENT</small><h1>{t.profile}</h1><div className="profile"><span>E</span><div><b>EVO Guest</b><small>Demo client profile</small></div></div><button className="row" onClick={()=>setScreen("booking")}>{t.booking}<em>→</em></button><button className="row" onClick={()=>setScreen("services")}>{t.services}<em>→</em></button></div>}
</section><nav>{[["⌂",t.home,"home"],["◇",t.services,"services"],["＋",t.booking,"booking"],["✦","AI","ai"],["○",t.profile,"profile"]].map(([ic,lab,id])=><button key={id} className={screen===id?"on":""} onClick={()=>setScreen(id as Screen)}><span>{ic}</span><small>{lab}</small></button>)}</nav></main>}
