import type { Lang } from "../data/evo";

export const ui = {
  ru: {
    nav:{home:"Главная",services:"Услуги",booking:"Запись",ai:"ИИ",profile:"Профиль"},
    common:{back:"Назад",next:"Продолжить",book:"Записаться",details:"Подробнее",choose:"Выбрать",close:"Закрыть",cancel:"Отменить",save:"Сохранить",demo:"Демо",all:"Все"},
    home:{eyebrow:"EVO BEAUTY SPACE · NHA TRANG",title:"Красота и косметология в одном MiniApp",lead:"Услуги, реальные специалисты EVO, запись, профиль и консультант — в едином мобильном интерфейсе.",open:"Онлайн-запись доступна",consult:"Консультация косметолога",popular:"Популярные направления",specialists:"Специалисты EVO",all:"Смотреть все",contacts:"Контакты и локация",route:"Открыть карту"},
    services:{title:"Услуги",lead:"Актуальный косметологический каталог EVO NORTH загружен из Altegio: реальные позиции, цены и связи со специалистами.",price:"Актуальная цена",duration:"Длительность",specialists:"Кто выполняет",book:"Записаться на процедуру",empty:"Услуги не найдены",search:"Поиск по 74 процедурам",allCategories:"Все направления",found:"Найдено"},
    specialists:{title:"Специалисты",lead:"Реальные профили и связи с процедурами получены из публичного каталога EVO NORTH. Если Altegio не вернул прямую связь, это явно отмечено.",demo:"Выбор в Altegio",services:"Услуги специалиста"},
    booking:{title:"Запись",demo:"Демо-запись сохраняется на этом устройстве и не отправляется в EVO. Для реальной записи используйте официальный Altegio.",stepService:"Услуга",stepSpecialist:"Специалист",stepDate:"Дата",stepTime:"Время",stepContact:"Контакты",stepReview:"Проверка",chooseService:"Выберите услугу",chooseSpecialist:"Выберите специалиста",chooseDate:"Выберите дату",chooseTime:"Выберите время",yourDetails:"Ваши данные",name:"Имя",phone:"Телефон / Telegram",email:"Email",review:"Проверьте запись",confirm:"Создать демо-запись",success:"Демо-запись создана",successNote:"Она появилась в профиле. Реальная запись в EVO оформляется через официальный Altegio.",openAltegio:"Открыть реальную запись EVO",noSpecialists:"Для этой процедуры специалист выбирается в официальной форме EVO.",searchService:"Найти процедуру"},
    ai:{title:"EVO AI · DEMO",lead:"Консультант использует свежий каталог EVO NORTH и помогает сориентироваться по направлениям. Диагнозы и медицинские назначения не выдаёт.",placeholder:"Например: что выбрать для качества кожи?",ask:"Спросить",hello:"Опишите цель или процедуру, которая вас интересует. Я предложу подходящие позиции из текущего каталога EVO.",fallback:"По этому запросу я не нашёл точного совпадения. Начните с консультации косметолога — специалист оценит кожу, цели и противопоказания.",recommend:"Подходящие направления:"},
    profile:{title:"Профиль",guest:"Гость EVO",demo:"Локальный demo-профиль",appointments:"Мои записи",empty:"Записей пока нет",emptyNote:"Создайте демо-запись, чтобы проверить полный сценарий MiniApp.",repeat:"Повторить",delete:"Удалить"},
    admin:{title:"Demo Admin",lead:"Демонстрационная административная часть. Каталог — реальный Altegio, записи и клиенты пока локальные на этом устройстве.",appointments:"Записи",clients:"Клиенты",catalog:"Услуги",broadcast:"Рассылка",noAppointments:"Локальных записей пока нет",broadcastText:"Текст рассылки",broadcastDemo:"Сохранить demo-рассылку",saved:"Demo-рассылка сохранена локально",statsAppointments:"Записей",statsClients:"Клиентов",statsServices:"Услуг",source:"Источник каталога"},
    location:{title:"EVO Beauty Space",book:"Altegio",map:"Карта",telegram:"Telegram администратора"}
  },
  en: {
    nav:{home:"Home",services:"Services",booking:"Booking",ai:"AI",profile:"Profile"},
    common:{back:"Back",next:"Continue",book:"Book",details:"Details",choose:"Choose",close:"Close",cancel:"Cancel",save:"Save",demo:"Demo",all:"All"},
    home:{eyebrow:"EVO BEAUTY SPACE · NHA TRANG",title:"Beauty and cosmetology in one MiniApp",lead:"Services, real EVO specialists, booking, profile and consultant in one mobile interface.",open:"Online booking available",consult:"Cosmetology consultation",popular:"Popular directions",specialists:"EVO specialists",all:"View all",contacts:"Contacts & location",route:"Open map"},
    services:{title:"Services",lead:"The current EVO NORTH cosmetology catalog is loaded from Altegio with real services, prices and staff mappings.",price:"Current price",duration:"Duration",specialists:"Performed by",book:"Book this treatment",empty:"No services found",search:"Search 74 treatments",allCategories:"All categories",found:"Found"},
    specialists:{title:"Specialists",lead:"Real profiles and service mappings are sourced from the public EVO NORTH catalog. Missing direct staff links are explicitly marked.",demo:"Select in Altegio",services:"Specialist services"},
    booking:{title:"Booking",demo:"Demo appointments are stored on this device and are not sent to EVO. Use official Altegio for a real appointment.",stepService:"Service",stepSpecialist:"Specialist",stepDate:"Date",stepTime:"Time",stepContact:"Contact",stepReview:"Review",chooseService:"Choose a service",chooseSpecialist:"Choose a specialist",chooseDate:"Choose a date",chooseTime:"Choose a time",yourDetails:"Your details",name:"Name",phone:"Phone / Telegram",email:"Email",review:"Review appointment",confirm:"Create demo appointment",success:"Demo appointment created",successNote:"It is now visible in Profile. Use official Altegio for a real EVO booking.",openAltegio:"Open real EVO booking",noSpecialists:"Choose an available specialist in the official EVO booking form.",searchService:"Find a treatment"},
    ai:{title:"EVO AI · DEMO",lead:"The consultant uses the current EVO NORTH catalog to help navigate services. It does not diagnose or prescribe treatment.",placeholder:"For example: what should I choose for skin quality?",ask:"Ask",hello:"Describe your goal or the treatment you are interested in. I will suggest relevant options from the current EVO catalog.",fallback:"I could not find an exact catalog match. Start with a cosmetology consultation so a specialist can assess your skin, goals and contraindications.",recommend:"Relevant options:"},
    profile:{title:"Profile",guest:"EVO Guest",demo:"Local demo profile",appointments:"My appointments",empty:"No appointments yet",emptyNote:"Create a demo appointment to test the full MiniApp flow.",repeat:"Repeat",delete:"Delete"},
    admin:{title:"Demo Admin",lead:"Demonstration admin area. The catalog is real Altegio data; appointments and clients are still local to this device.",appointments:"Appointments",clients:"Clients",catalog:"Services",broadcast:"Broadcast",noAppointments:"No local appointments yet",broadcastText:"Broadcast text",broadcastDemo:"Save demo broadcast",saved:"Demo broadcast saved locally",statsAppointments:"Appointments",statsClients:"Clients",statsServices:"Services",source:"Catalog source"},
    location:{title:"EVO Beauty Space",book:"Altegio",map:"Map",telegram:"Administrator Telegram"}
  },
  vi: {
    nav:{home:"Trang chủ",services:"Dịch vụ",booking:"Đặt lịch",ai:"AI",profile:"Hồ sơ"},
    common:{back:"Quay lại",next:"Tiếp tục",book:"Đặt lịch",details:"Chi tiết",choose:"Chọn",close:"Đóng",cancel:"Hủy",save:"Lưu",demo:"Demo",all:"Tất cả"},
    home:{eyebrow:"EVO BEAUTY SPACE · NHA TRANG",title:"Làm đẹp và thẩm mỹ trong một MiniApp",lead:"Dịch vụ, chuyên gia EVO thực tế, đặt lịch, hồ sơ và tư vấn trong một giao diện di động.",open:"Có thể đặt lịch trực tuyến",consult:"Tư vấn thẩm mỹ",popular:"Dịch vụ nổi bật",specialists:"Chuyên gia EVO",all:"Xem tất cả",contacts:"Liên hệ & địa điểm",route:"Mở bản đồ"},
    services:{title:"Dịch vụ",lead:"Danh mục thẩm mỹ EVO NORTH hiện tại được tải từ Altegio với dịch vụ, giá và liên kết chuyên gia thực tế.",price:"Giá hiện tại",duration:"Thời lượng",specialists:"Chuyên gia thực hiện",book:"Đặt lịch dịch vụ",empty:"Không tìm thấy dịch vụ",search:"Tìm trong 74 dịch vụ",allCategories:"Tất cả nhóm dịch vụ",found:"Tìm thấy"},
    specialists:{title:"Chuyên gia",lead:"Hồ sơ thực tế và liên kết dịch vụ được lấy từ danh mục công khai EVO NORTH. Các dịch vụ chưa có liên kết trực tiếp sẽ được đánh dấu rõ ràng.",demo:"Chọn trong Altegio",services:"Dịch vụ của chuyên gia"},
    booking:{title:"Đặt lịch",demo:"Lịch demo chỉ được lưu trên thiết bị này và chưa gửi tới EVO. Hãy dùng Altegio chính thức để đặt lịch thật.",stepService:"Dịch vụ",stepSpecialist:"Chuyên gia",stepDate:"Ngày",stepTime:"Giờ",stepContact:"Liên hệ",stepReview:"Kiểm tra",chooseService:"Chọn dịch vụ",chooseSpecialist:"Chọn chuyên gia",chooseDate:"Chọn ngày",chooseTime:"Chọn giờ",yourDetails:"Thông tin của bạn",name:"Họ tên",phone:"Điện thoại / Telegram",email:"Email",review:"Kiểm tra lịch hẹn",confirm:"Tạo lịch demo",success:"Đã tạo lịch demo",successNote:"Lịch đã xuất hiện trong Hồ sơ. Để đặt lịch thật tại EVO, hãy dùng Altegio chính thức.",openAltegio:"Mở đặt lịch EVO thật",noSpecialists:"Hãy chọn chuyên gia khả dụng trong biểu mẫu đặt lịch chính thức của EVO.",searchService:"Tìm dịch vụ"},
    ai:{title:"EVO AI · DEMO",lead:"Trợ lý sử dụng danh mục EVO NORTH hiện tại để định hướng dịch vụ. Không chẩn đoán hay kê chỉ định y khoa.",placeholder:"Ví dụ: nên chọn gì để cải thiện chất lượng da?",ask:"Hỏi",hello:"Hãy mô tả mục tiêu hoặc dịch vụ bạn quan tâm. Tôi sẽ gợi ý các lựa chọn phù hợp từ danh mục EVO hiện tại.",fallback:"Tôi chưa tìm thấy lựa chọn khớp chính xác. Hãy bắt đầu bằng tư vấn thẩm mỹ để chuyên gia đánh giá da, mục tiêu và chống chỉ định.",recommend:"Các lựa chọn phù hợp:"},
    profile:{title:"Hồ sơ",guest:"Khách EVO",demo:"Hồ sơ demo cục bộ",appointments:"Lịch hẹn của tôi",empty:"Chưa có lịch hẹn",emptyNote:"Tạo một lịch demo để kiểm tra đầy đủ quy trình MiniApp.",repeat:"Đặt lại",delete:"Xóa"},
    admin:{title:"Demo Admin",lead:"Khu vực quản trị demo. Danh mục là dữ liệu Altegio thực tế; lịch hẹn và khách hàng hiện vẫn lưu cục bộ trên thiết bị.",appointments:"Lịch hẹn",clients:"Khách hàng",catalog:"Dịch vụ",broadcast:"Gửi tin",noAppointments:"Chưa có lịch hẹn cục bộ",broadcastText:"Nội dung tin",broadcastDemo:"Lưu bản demo",saved:"Đã lưu bản demo cục bộ",statsAppointments:"Lịch hẹn",statsClients:"Khách hàng",statsServices:"Dịch vụ",source:"Nguồn danh mục"},
    location:{title:"EVO Beauty Space",book:"Altegio",map:"Bản đồ",telegram:"Telegram quản trị viên"}
  }
} as const;

export type Ui = typeof ui.ru;
