import type { Lang } from "../data/evo";

export const ui = {
  ru: {
    nav:{home:"Главная",services:"Услуги",booking:"Запись",ai:"ИИ",profile:"Профиль"},
    common:{back:"Назад",next:"Продолжить",book:"Записаться",details:"Подробнее",choose:"Выбрать",close:"Закрыть",cancel:"Отменить",save:"Сохранить",demo:"Демо"},
    home:{eyebrow:"EVO BEAUTY SPACE · NHA TRANG",title:"Красота и косметология в одном MiniApp",lead:"Услуги, специалисты, запись, профиль и консультант — в едином мобильном интерфейсе.",open:"Онлайн-запись доступна",consult:"Консультация косметолога",popular:"Популярные направления",specialists:"Специалисты EVO",all:"Смотреть все",contacts:"Контакты и локация",route:"Открыть карту"},
    services:{title:"Услуги",lead:"Каталог структурирован отдельно от интерфейса и готов к автоматической синхронизации с Altegio.",price:"Актуальная цена",duration:"Длительность",specialists:"Кто выполняет",book:"Записаться на процедуру",empty:"Услуги не найдены"},
    specialists:{title:"Специалисты",lead:"До получения свежего Altegio-каталога показаны честно помеченные demo-профили. После синхронизации они заменяются реальными данными без изменения UI.",demo:"Демо-профиль",services:"Услуги специалиста"},
    booking:{title:"Запись",demo:"Демо-запись сохраняется на этом устройстве и не отправляется в EVO. Для реальной записи используйте Altegio.",stepService:"Услуга",stepSpecialist:"Специалист",stepDate:"Дата",stepTime:"Время",stepContact:"Контакты",stepReview:"Проверка",chooseService:"Выберите услугу",chooseSpecialist:"Выберите специалиста",chooseDate:"Выберите дату",chooseTime:"Выберите время",yourDetails:"Ваши данные",name:"Имя",phone:"Телефон / Telegram",email:"Email",review:"Проверьте запись",confirm:"Создать демо-запись",success:"Демо-запись создана",successNote:"Она появилась в профиле. Реальная запись в EVO оформляется через официальный Altegio.",openAltegio:"Открыть реальную запись EVO",noSpecialists:"Для услуги пока нет специалиста в demo-каталоге."},
    ai:{title:"EVO AI · DEMO",lead:"Консультант использует текущий каталог MiniApp и помогает сориентироваться по направлениям. Диагнозы и медицинские назначения не выдаёт.",placeholder:"Например: что выбрать для качества кожи?",ask:"Спросить",hello:"Опишите цель или процедуру, которая вас интересует. Я предложу подходящие направления из каталога EVO.",fallback:"По этому запросу я не нашёл точного совпадения. Начните с консультации косметолога — специалист оценит кожу, цели и противопоказания.",recommend:"Подходящие направления:"},
    profile:{title:"Профиль",guest:"Гость EVO",demo:"Локальный demo-профиль",appointments:"Мои записи",empty:"Записей пока нет",emptyNote:"Создайте демо-запись, чтобы проверить полный сценарий MiniApp.",repeat:"Повторить",delete:"Удалить"},
    admin:{title:"Demo Admin",lead:"Демонстрационная административная часть. Данные берутся из локальных записей этого устройства; отправка и база будут подключены на следующем этапе.",appointments:"Записи",clients:"Клиенты",catalog:"Услуги",broadcast:"Рассылка",noAppointments:"Локальных записей пока нет",broadcastText:"Текст рассылки",broadcastDemo:"Сохранить demo-рассылку",saved:"Demo-рассылка сохранена локально",statsAppointments:"Записей",statsClients:"Клиентов",statsServices:"Услуг"},
    location:{title:"EVO Beauty Space",book:"Altegio",map:"Карта"}
  },
  en: {
    nav:{home:"Home",services:"Services",booking:"Booking",ai:"AI",profile:"Profile"},
    common:{back:"Back",next:"Continue",book:"Book",details:"Details",choose:"Choose",close:"Close",cancel:"Cancel",save:"Save",demo:"Demo"},
    home:{eyebrow:"EVO BEAUTY SPACE · NHA TRANG",title:"Beauty and cosmetology in one MiniApp",lead:"Services, specialists, booking, profile and consultant in one mobile interface.",open:"Online booking available",consult:"Cosmetology consultation",popular:"Popular directions",specialists:"EVO specialists",all:"View all",contacts:"Contacts & location",route:"Open map"},
    services:{title:"Services",lead:"The catalog is separated from UI and ready for automated Altegio synchronization.",price:"Current price",duration:"Duration",specialists:"Performed by",book:"Book this treatment",empty:"No services found"},
    specialists:{title:"Specialists",lead:"Until a fresh Altegio catalog is available, clearly marked demo profiles are shown. They can be replaced by real records without changing the UI.",demo:"Demo profile",services:"Specialist services"},
    booking:{title:"Booking",demo:"Demo appointments are stored on this device and are not sent to EVO. Use Altegio for a real appointment.",stepService:"Service",stepSpecialist:"Specialist",stepDate:"Date",stepTime:"Time",stepContact:"Contact",stepReview:"Review",chooseService:"Choose a service",chooseSpecialist:"Choose a specialist",chooseDate:"Choose a date",chooseTime:"Choose a time",yourDetails:"Your details",name:"Name",phone:"Phone / Telegram",email:"Email",review:"Review appointment",confirm:"Create demo appointment",success:"Demo appointment created",successNote:"It is now visible in Profile. Use official Altegio for a real EVO booking.",openAltegio:"Open real EVO booking",noSpecialists:"No specialist is available for this service in the demo catalog yet."},
    ai:{title:"EVO AI · DEMO",lead:"The consultant uses the current MiniApp catalog to help navigate services. It does not diagnose or prescribe treatment.",placeholder:"For example: what should I choose for skin quality?",ask:"Ask",hello:"Describe your goal or the treatment you are interested in. I will suggest relevant EVO catalog directions.",fallback:"I could not find an exact catalog match. Start with a cosmetology consultation so a specialist can assess your skin, goals and contraindications.",recommend:"Relevant options:"},
    profile:{title:"Profile",guest:"EVO Guest",demo:"Local demo profile",appointments:"My appointments",empty:"No appointments yet",emptyNote:"Create a demo appointment to test the full MiniApp flow.",repeat:"Repeat",delete:"Delete"},
    admin:{title:"Demo Admin",lead:"Demonstration admin area. Data comes from local appointments on this device; delivery and a shared database come later.",appointments:"Appointments",clients:"Clients",catalog:"Services",broadcast:"Broadcast",noAppointments:"No local appointments yet",broadcastText:"Broadcast text",broadcastDemo:"Save demo broadcast",saved:"Demo broadcast saved locally",statsAppointments:"Appointments",statsClients:"Clients",statsServices:"Services"},
    location:{title:"EVO Beauty Space",book:"Altegio",map:"Map"}
  },
  vi: {
    nav:{home:"Trang chủ",services:"Dịch vụ",booking:"Đặt lịch",ai:"AI",profile:"Hồ sơ"},
    common:{back:"Quay lại",next:"Tiếp tục",book:"Đặt lịch",details:"Chi tiết",choose:"Chọn",close:"Đóng",cancel:"Hủy",save:"Lưu",demo:"Demo"},
    home:{eyebrow:"EVO BEAUTY SPACE · NHA TRANG",title:"Làm đẹp và thẩm mỹ trong một MiniApp",lead:"Dịch vụ, chuyên gia, đặt lịch, hồ sơ và tư vấn trong một giao diện di động.",open:"Có thể đặt lịch trực tuyến",consult:"Tư vấn thẩm mỹ",popular:"Dịch vụ nổi bật",specialists:"Chuyên gia EVO",all:"Xem tất cả",contacts:"Liên hệ & địa điểm",route:"Mở bản đồ"},
    services:{title:"Dịch vụ",lead:"Danh mục được tách khỏi giao diện và sẵn sàng đồng bộ tự động với Altegio.",price:"Giá hiện tại",duration:"Thời lượng",specialists:"Chuyên gia thực hiện",book:"Đặt lịch dịch vụ",empty:"Không tìm thấy dịch vụ"},
    specialists:{title:"Chuyên gia",lead:"Cho đến khi có danh mục Altegio mới, ứng dụng hiển thị hồ sơ demo được đánh dấu rõ ràng. Sau đồng bộ chúng sẽ được thay bằng dữ liệu thực mà không đổi UI.",demo:"Hồ sơ demo",services:"Dịch vụ của chuyên gia"},
    booking:{title:"Đặt lịch",demo:"Lịch demo chỉ được lưu trên thiết bị này và chưa gửi tới EVO. Hãy dùng Altegio để đặt lịch thật.",stepService:"Dịch vụ",stepSpecialist:"Chuyên gia",stepDate:"Ngày",stepTime:"Giờ",stepContact:"Liên hệ",stepReview:"Kiểm tra",chooseService:"Chọn dịch vụ",chooseSpecialist:"Chọn chuyên gia",chooseDate:"Chọn ngày",chooseTime:"Chọn giờ",yourDetails:"Thông tin của bạn",name:"Họ tên",phone:"Điện thoại / Telegram",email:"Email",review:"Kiểm tra lịch hẹn",confirm:"Tạo lịch demo",success:"Đã tạo lịch demo",successNote:"Lịch đã xuất hiện trong Hồ sơ. Để đặt lịch thật tại EVO, hãy dùng Altegio chính thức.",openAltegio:"Mở đặt lịch EVO thật",noSpecialists:"Chưa có chuyên gia cho dịch vụ này trong danh mục demo."},
    ai:{title:"EVO AI · DEMO",lead:"Trợ lý sử dụng danh mục hiện tại của MiniApp để định hướng dịch vụ. Không chẩn đoán hay kê chỉ định y khoa.",placeholder:"Ví dụ: nên chọn gì để cải thiện chất lượng da?",ask:"Hỏi",hello:"Hãy mô tả mục tiêu hoặc dịch vụ bạn quan tâm. Tôi sẽ gợi ý các lựa chọn phù hợp trong danh mục EVO.",fallback:"Tôi chưa tìm thấy lựa chọn khớp chính xác. Hãy bắt đầu bằng tư vấn thẩm mỹ để chuyên gia đánh giá da, mục tiêu và chống chỉ định.",recommend:"Các lựa chọn phù hợp:"},
    profile:{title:"Hồ sơ",guest:"Khách EVO",demo:"Hồ sơ demo cục bộ",appointments:"Lịch hẹn của tôi",empty:"Chưa có lịch hẹn",emptyNote:"Tạo một lịch demo để kiểm tra đầy đủ quy trình MiniApp.",repeat:"Đặt lại",delete:"Xóa"},
    admin:{title:"Demo Admin",lead:"Khu vực quản trị demo. Dữ liệu lấy từ lịch hẹn cục bộ trên thiết bị; gửi dữ liệu và cơ sở dữ liệu chung sẽ được kết nối sau.",appointments:"Lịch hẹn",clients:"Khách hàng",catalog:"Dịch vụ",broadcast:"Gửi tin",noAppointments:"Chưa có lịch hẹn cục bộ",broadcastText:"Nội dung tin",broadcastDemo:"Lưu bản demo",saved:"Đã lưu bản demo cục bộ",statsAppointments:"Lịch hẹn",statsClients:"Khách hàng",statsServices:"Dịch vụ"},
    location:{title:"EVO Beauty Space",book:"Altegio",map:"Bản đồ"}
  }
} as const;

export type Ui = typeof ui.ru;
